# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  displayName:  "Checking out repo"
- task: HugoTask@2
  inputs:
    source: '/'
    destination: '$(Build.ArtifactStagingDirectory)'
    baseURL: 'https://beta.oyvindmal.no'